---
# tasks file for patroni

- name: Install OpenStack repo for etcd
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux') and ansible_distribution_version.startswith('8') 
  dnf:
    name: https://repo.percona.com/ppg-16.2/yum/release/8/RPMS/x86_64/etcd-3.5.12-1.el8.x86_64.rpm
    state: present
    disable_gpg_check: yes

- name: install Etcd
  package:
    name: "etcd"
    state: present

- name: Install patroni
  command:
    cmd: /bin/bash /vagrant/tools/install_patroni.sh "{{ 'yes' if 'development' in db_features.split(',') else '' }}"
    creates: "'/usr/local/bin/patroni' if 'development' in db_features.split(',') else '/usr/bin/patroni'"

- name: Patroni Setup tasks
  when: install_only == ''
  include_tasks: setup.yaml
