---
# vars file for mongodb
pkg_prefix: "{{ psmdb_name+psmdb_major_ver if psmdb_version != '' else 'mongodb-org' }}"
pkg_version: "{{ psmdb_version if psmdb_version != '' else mongo_org_version }}"
pkg_major: "{{ pkg_version | regex_search('^[0-9]+[.][0-9]+') }}"
pkg:
  el7:
    install_packages:
      - "{{ pkg_prefix }}-tools-{{ pkg_version }}.{{ dist }}.x86_64"
      - "{{ pkg_prefix }}-shell-{{ pkg_version }}.{{ dist }}.x86_64"
      - "{{ pkg_prefix }}-server-{{ pkg_version }}.{{ dist }}.x86_64"
      - "{{ pkg_prefix }}-mongos-{{ pkg_version }}.{{ dist }}.x86_64"
      - "{{ pkg_prefix }}-{{ pkg_version }}.{{ dist }}.x86_64"
  el8:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-{{ psmdb_version }}.{{ dist }}.x86_64"
  stretch:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}={{ psmdb_version }}.{{ dist }}"
  buster:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}={{ psmdb_version }}.{{ dist }}"
  bionic:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}={{ psmdb_version }}.{{ dist }}"
  focal:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}={{ psmdb_version }}.{{ dist }}"
mongos_log: "{{ '/var/log/mongo/mongos.log' if (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux') else '/var/log/mongodb/mongos.log' }}"
mongos_keyfile: "{{ mongos_cfg | regex_replace('^([^/]*)/.*$', '\\1') }}-keyfile"
