#!/bin/bash
ADMIN_PASSWORD="${1:-MyPassword2026}"
REALM=EXAMPLE.NET
DOMAIN=EXAMPLE

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install samba winbind bind9-dnsutils ldap-utils krb5-user net-tools iputils-ping

rm -f /etc/samba/smb.conf
samba-tool domain provision --realm "$REALM" --domain "$DOMAIN" --adminpass="$ADMIN_PASSWORD" --option="ldap server require strong auth=No"

# Create test users
samba-tool user add dbauser01 --surname=User01 --given-name=Dba --mail-address=dbauser01@example.net DbaPassword1
samba-tool user add dbauser02 --surname=User02 --given-name=Dba2 --mail-address=dbauser02@example.net DbaPassword2
samba-tool user add dbauser03 --surname=User03 --given-name=Dba3 --mail-address=dbauser03@example.net DbaPassword3
samba-tool user add devuser01 --surname=User01 --given-name=Dev --mail-address=devuser01@example.net DevPassword1
samba-tool user add devuser02 --surname=User02 --given-name=Dev2 --mail-address=devuser02@example.net DevPassword2
samba-tool user add devuser03 --surname=User03 --given-name=Dev3 --mail-address=devuser03@example.net DevPassword3

# Copy Kerberos config generated by Samba and add explicit KDC address
SAMBA_IP=$(hostname -I | awk '{print $1}')
cat > /etc/krb5.conf << EOF
[libdefaults]
    default_realm = ${REALM}
    dns_lookup_realm = false
    dns_lookup_kdc = false

[realms]
${REALM} = {
    kdc = ${SAMBA_IP}
    admin_server = ${SAMBA_IP}
    default_domain = $(echo ${REALM} | tr '[:upper:]' '[:lower:]')
}

[domain_realm]
    .$(echo ${REALM} | tr '[:upper:]' '[:lower:]') = ${REALM}
    $(echo ${REALM} | tr '[:upper:]' '[:lower:]') = ${REALM}
EOF

# Start Samba
samba

# Use Samba's built-in DNS
echo "nameserver 127.0.0.1" > /etc/resolv.conf

touch /root/kerberos-samba.configured
